targets:
  arangodb:
    module: arangodb
    endpoint: http://arango.default:8529
    database: _system
    username: root
    password: root
  yugabyte:
    module: postgres
    connection_string: "host=yb-tservers.default port=5433 dbname=postgres user=yugabyte"
  cockroachdb:
    module: postgres
    connection_string: "host=cockroachdb-public.default.svc.cluster.local port=26257 dbname=postgres"
  postgresql:
    module: postgres
    connection_string: "host=postgres-postgresql.default port=5432 dbname=postgres user=postgres password=postgres"
  cassandra:
    module: cassandra
    contact_points: "k8ssandra-bench-dc1-service"
    keyspace: "benchmark"
    replication_factor: 3
    consistency_level: "LOCAL_QUORUM"
    max_sync_calls: 1
    device_spread: 1
namespace: default
