---
namespace: default
target_module: azure_data_explorer
run_config: ewoidGFzayI6ICJxdWVyeSIsCiJ1c2VfbXVsdGlwbGVfdGFibGVzIjogZmFsc2UsCiJjbGVhbl9kYXRhYmFzZSI6IHRydWUsCiJiYXRjaF9tb2RlIjogdHJ1ZSwKInByZWZpbGwiOiAwLAoicnVucyI6IDMsCiJudW1faW5zZXJ0cyI6IDEwMDAwLAoia3VzdG9fdXJpIjogImh0dHBzOi8vYWR4Y29tcGFyZS53ZXN0ZXVyb3BlLmt1c3RvLndpbmRvd3MubmV0IiwKImt1c3RvX2luZ2VzdF91cmkiOiAiaHR0cHM6Ly9pbmdlc3QtYWR4Y29tcGFyZS53ZXN0ZXVyb3BlLmt1c3RvLndpbmRvd3MubmV0IiwKImt1c3RvX2RiIjogIlNhbXBsZURCIgp9
workers: 1

image:
  name: davidboettcher/database-comparison
  tag: latest

nodeSelector: {}
  #workload: client