apiVersion: database.arangodb.com/v1alpha
kind: ArangoDeployment
metadata:
  name: arango
spec:
  # mode: Single
  mode: Cluster
  dbservers:
    count: 3
    # resources:
    #   requests:
    #     cpu: 7
    #     memory: 5Gi
    #   limits:
    #     cpu: 8
    #     memory: 10G
  tls:
    caSecretName: None
  image: arangodb/arangodb:3.6.1
  auth:
    jwtSecretName: None
