storage:
  persistentVolume:
    size: 5Gi
statefulset:
  replicas: 3
  resources:
    limits:
      cpu: "8"
      memory: "16Gi"
    requests:
      cpu: "7"
      memory: "8Gi"
  # nodeSelector:
  #   workload: db
conf:
  #single-node: true
  cache: "2Gi"
  max-sql-memory: "2Gi"
tls:
  enabled: false
